"""Generate circmean_table.h (quarter-wave sine, Q15, 0.1-degree steps).

Run:  python gen_table.py > circmean_table.h   (committed output)

Also importable: sin_q15/cordic_atan2_001deg are the integer REFERENCE
implementation mirrored line-for-line by circmean.c — test_circmean.py
validates the algorithm against these before the C runs on target.
"""

import math

N = 901  # 0.0 .. 90.0 degrees in 0.1-degree steps


def table():
    return [min(32767, round(math.sin(math.radians(i / 10.0)) * 32768))
            for i in range(N)]


def sin_q15(a):  # a in 0.1 deg, 0..3599
    tab = table()
    q, r = divmod(a, 900)
    if q == 0:
        return tab[r]
    if q == 1:
        return tab[900 - r]
    if q == 2:
        return -tab[r]
    return -tab[900 - r]


def cos_q15(a):
    return sin_q15((a + 900) % 3600)


# CORDIC vectoring, 16 iterations, angle unit 0.001 degree.
ATAN_001DEG = [round(math.degrees(math.atan(2.0 ** -i)) * 1000) for i in range(16)]


def cordic_atan2_001deg(y, x):
    """atan2 in 0..359999 (0.001 deg). Integer ops only."""
    if x == 0 and y == 0:
        return 0
    # Fold to right half-plane
    if x < 0:
        flip = True
        x, y = -x, -y
    else:
        flip = False
    # Normalise magnitude below 2^26 so the 1.647 CORDIC growth fits int32
    while abs(x) >= (1 << 26) or abs(y) >= (1 << 26):
        x >>= 1
        y >>= 1
    ang = 0
    for i in range(16):
        if y > 0:
            x, y = x + (y >> i), y - (x >> i)
            ang += ATAN_001DEG[i]
        else:
            x, y = x - (y >> i), y + (x >> i)
            ang -= ATAN_001DEG[i]
    if flip:
        ang += 180000  # folded by point reflection: rotate back, don't mirror
    return ang % 360000


def circmean_ref(angles_01deg):
    """Reference circular mean: 0..3599, or 65535 for no samples."""
    if not angles_01deg:
        return 65535
    ss = sum(sin_q15(a) for a in angles_01deg)
    sc = sum(cos_q15(a) for a in angles_01deg)
    a001 = cordic_atan2_001deg(ss, sc)
    return ((a001 + 50) // 100) % 3600


if __name__ == "__main__":
    tab = table()
    print("// Generated by gen_table.py — do not edit by hand.")
    print("// Quarter-wave sine, Q15: sin(i * 0.1 deg) for i = 0..900.")
    print("#ifndef CIRCMEAN_TABLE_H")
    print("#define CIRCMEAN_TABLE_H")
    print("#include <stdint.h>")
    print(f"static const int16_t circmean_sin_tab[{N}] = {{")
    for i in range(0, N, 10):
        row = ", ".join(f"{v:6d}" for v in tab[i:i + 10])
        print(f"\t{row},")
    print("};")
    print("#endif")
